-- 创建留言表
CREATE TABLE IF NOT EXISTS guestbook (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 启用行级安全性
ALTER TABLE guestbook ENABLE ROW LEVEL SECURITY;

-- 创建策略：所有人都可以查看留言
CREATE POLICY "允许所有人查看留言"
    ON guestbook
    FOR SELECT
    USING (true);

-- 创建策略：所有人都可以添加留言
CREATE POLICY "允许所有人添加留言"
    ON guestbook
    FOR INSERT
    WITH CHECK (true);
